export type Need = { id: string; team: string; text: string; unblocks: string; group: string };
export const NEEDS: Need[] = [
  { id: "etsy-shop", team: "05", text: "Etsy seller account + shop name", unblocks: "publishing product-01/02", group: "Accounts & access" },
  { id: "pinterest-biz", team: "05", text: "Pinterest business account (Rich Pins)", unblocks: "traffic", group: "Accounts & access" },
  { id: "yt-channel", team: "02", text: "YouTube channel access", unblocks: "publishing first-video", group: "Accounts & access" },
  { id: "amazon-id", team: "02", text: "Amazon Associates ID", unblocks: "affiliate links", group: "Accounts & access" },
  { id: "gumroad", team: "06", text: "Gumroad account", unblocks: "GPT suite checkout", group: "Accounts & access" },
  { id: "tiktok-shop", team: "11", text: "TikTok Shop seller account", unblocks: "hero listing", group: "Accounts & access" },
  { id: "meta-ads", team: "11", text: "Meta ad account + pixel", unblocks: "$20/day tests", group: "Accounts & access" },
  { id: "pilot-salon", team: "08", text: "One pilot salon/dentist intro", unblocks: "first $199 retainer", group: "Accounts & access" },
  { id: "elevenlabs", team: "02·09", text: "ElevenLabs key (upgrade; v1 voices ship on local Piper)", unblocks: "studio warmth", group: "API keys" },
  { id: "llm-key", team: "01·06·08", text: "OpenAI/Anthropic key ($3–12/mo)", unblocks: "bots", group: "API keys" },
  { id: "firehose", team: "04", text: "X firehose ($49/mo) + Telegram bot token", unblocks: "signal bots", group: "API keys" },
  { id: "replicate", team: "07", text: "Replicate token", unblocks: "staging renders", group: "API keys" },
  { id: "twilio", team: "08", text: "Twilio number + GoHighLevel login", unblocks: "missed-call rescue", group: "API keys" },
  { id: "reddit-api", team: "03", text: "Reddit API credentials", unblocks: "miner at scale", group: "API keys" },
  { id: "budget-300", team: "11", text: "Approve ~$300 test budget", unblocks: "paid tests (P2)", group: "Money decisions" },
  { id: "firehose-budget", team: "04", text: "Approve $49/mo + Stripe/crypto rails", unblocks: "paid alert tier", group: "Money decisions" },
  { id: "gpu-float", team: "07", text: "Approve GPU float (~$20)", unblocks: "free-trial stages", group: "Money decisions" },
  { id: "voice-samples", team: "01", text: "Your past posts + one transcript", unblocks: "voice profile", group: "Only you have" },
  { id: "listing-photos", team: "07", text: "Three raw listing photos", unblocks: "realtor demo pack", group: "Only you have" },
  { id: "mom-testers", team: "09", text: "Five moms to test one track", unblocks: "pack release", group: "Only you have" },
  { id: "dog-groups", team: "11", text: "Three dog-owner group names", unblocks: "first $100 pre-sales", group: "Only you have" },
];
