export type Thesis = {
  id: string; n: string; title: string; pain: string; evidence: string;
  wedge: string; money: string; whyUs: string; status: string; related: string;
};
export const THESES: Thesis[] = [
  { id: "side-effect-safety", n: "T1", title: "Agent side-effect safety",
    pain: "Retries re-fire real actions — one crashed agent emailed a customer twice; benchmark agents invoiced $12k of fiction; 0.85^10 ≈ 0.20 reliability over ten steps.",
    evidence: "r/LangChain retry-nightmare thread (‘Retries are inevitable. Duplicate side effects don’t have to be.’) · HN invoice-fraud firestorm, Sep 2026 · Gartner: 40%+ agentic projects face cancellation.",
    wedge: "OSS idempotency ledger + tool-call receipts — exactly our Effect-typed bus pattern, extracted as a library every agent framework plugs into.",
    money: "Free core → hosted ledger + policy packs per seat.",
    whyUs: "We already run this pattern across 11 crews (bus/HANDOFF/approvals). Dogfood first, publish second.",
    status: "Thesis — pattern proven in-house, extraction queued.", related: "01" },
  { id: "context-metering", n: "T2", title: "Live context metering",
    pain: "32:1 token re-read ratios; $4.5k cached vs $31k uncached sessions; 41% of orgs paused AI projects over bill shock.",
    evidence: "IndieHackers TokenBar post (‘visibility changes behavior more than postmortems’) · Sep 2026 transcript audit: 1.99B tokens re-read across 3 sessions.",
    wedge: "Local live meter (menu bar / editor gutter / CLI) + auto-compact policies. Parses transcript JSONL — zero keys needed.",
    money: "Free meter → team rollups + budget guardrails.",
    whyUs: "Our orchestrator already emits per-task costs; we feel this pain daily.",
    status: "Thesis — spec ready, build queued.", related: "06" },
  { id: "context-compiler", n: "T3", title: "Cache-aligned context compiler",
    pain: "Memory tools torch KV-cache prefixes (12% hits vs 86% stateful); managed hops add 50–200ms per turn and full-price tokens.",
    evidence: "2026 context-engineering benchmarks: stateful compaction 89.5% pass at $0.86/run vs naive $11.42; Mem0/Letta/Zep prefix-cache analysis.",
    wedge: "Deterministic byte-stable context builder + live cache-hit dashboard. Boring, fast, honest.",
    money: "Gateway cut of saved spend.",
    whyUs: "Effect Schema gives us exact-shape context; our bus already versions every state.",
    status: "Thesis — spec ready, build queued.", related: "06" },
  { id: "eval-as-code", n: "T4", title: "Eval-as-code for indies",
    pain: "$249/mo eval platforms don't exist pre-PMF; prompt regressions ship silently and eat revenue.",
    evidence: "DEV indie guide: rubric + 20–50 goldens + cheap-judge CI at ~£0.20/run caught a context-drop in 4 minutes that manual testing missed.",
    wedge: "GitHub Action + golden-dataset templates for 6 use cases + threshold gates. Copy-paste, no tweaking.",
    money: "Free action → hosted trend dashboards + benchmark sharing.",
    whyUs: "Built for our own GPT suite first; we sell the scars.",
    status: "Thesis — building for Team 06 first.", related: "06" },
  { id: "safe-autonomy", n: "T5", title: "Safe-autonomy sandbox",
    pain: "Operators are liable for agent actions (‘pull the trigger, you did the murder’); compliance blocks every pilot.",
    evidence: "HN liability debate on autonomous-business benchmark · Gartner cancellations cite weak risk controls.",
    wedge: "Default-deny runtime: allowlisted tools, spend caps, human-gate queues, full audit trail — our approvals queue, hardened.",
    money: "OSS runtime → enterprise policy packs + audit exports.",
    whyUs: "Our approvals + bus IS v0. Extract, harden, publish.",
    status: "Thesis — v0 running in-house.", related: "08" },
  { id: "local-voice", n: "T6", title: "Sub-second local voice loop",
    pain: "Cloud voice pipelines = 1–3s dead air with no interruption; local models lack streaming glue; clinics can't send audio to the cloud at all.",
    evidence: "Voice-agent latency breakdowns across forums; our own sleep pipeline needed local Piper to ship key-free.",
    wedge: "Local loop kit (VAD + streaming STT + small LLM + Piper-class TTS) with a per-stage latency budget dashboard. One machine, zero keys.",
    money: "Hosted voices, on-prem boxes, per-minute support.",
    whyUs: "Our sleep-audio + video pipeline is the demo; Piper test passed in-house.",
    status: "Thesis — voice proven, loop kit queued.", related: "09" },
];
